### PR TITLE
avoid namespace conflict

### PR DESCRIPTION
**Pull request by cerdiogenes**

### CODE REVIEW

**Comment by cerdiogenes** [comment]
The commit [684d4e8](https://github.com/cerdiogenes/paloma/commit/684d4e8db0c1b13357e084cac85dc18305c45d7a) is another solution to insert the html hook. It's has less impact than the solution proposed in #69.

**Comment by kbparagua** [comment]
@cerdiogenes Thanks for this! But I'm leaning towards to removing the magic *(it is confusing and can really cause a lot of trouble)* using the proposed solution in #69. Anyway, thanks again :+1:

**Comment by cerdiogenes** [comment]
The commit [b15acaa](https://github.com/cerdiogenes/paloma/commit/b15acaaa153239f3090ccb0c78cb6645be02197a) is about conflict between controller and modules as explained in [gotchas](https://github.com/kbparagua/paloma#gotchas). Do you have interest in this? I can submit another PR only with this.

**Comment by kbparagua** [comment]
@cerdiogenes Yes. Please submit another PR and I'll review it. Thank you!

**Pull request closed without merging**
